name: thunderlanchonete
description: ThundeRatz snack bar.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.3
  google_sign_in: ^4.1.1
  wave: ^0.0.8
  fluttertoast: ^3.1.3
  flutter_svg: ^0.17.1
  flare_flutter: ^2.0.1
  intl: ^0.16.1
  curved_navigation_bar: ^0.3.2
  firebase_storage: ^3.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ThunderLanchonete.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: BrandonText
      fonts:
        - asset: fonts/BrandonText-Black.ttf
          weight: 900
